### PR TITLE
Updating Rule Sets to incoporate Threat Intelligence

### PR DESCRIPTION
**Pull request by liceaga**
This PR is to will update threatstack agents on the boxes to deploy with the new threatstack feature called "cloud security platform"

### CODE REVIEW

**Comment by dennyabraham** [comment]
the syntax looks right :+1:

**Comment by pmahoney-raise** [comment]
Can this be configured via attributes in our chef configurations rather than by modifying a third-party recipe?  Or are we OK maintaining our own (public) fork of threatstack-chef?

**Comment by liceaga** [comment]
@pmahoney-raise possibly, I'd have to defer to @gregpalmier on that one. Either works for me.

**Comment by rickalm** [comment]
Please remove me from the repo

----
Thanks, Rick

<div>-------- Original message --------</div><div>From: leece <notifications@github.com> </div><div>Date:02/22/2016  10:35 AM  (GMT-06:00) </div><div>To: CouponTrade/threatstack-chef <threatstack-chef@noreply.github.com> </div><div>Subject: Re: [threatstack-chef] Updating Rule Sets to incoporate Threat
  Intelligence (#2) </div><div>
</div>@pmahoney-raise possibly, I'd have to defer to @gregpalmier on that one. Either works for me.

**Comment by gregpalmier** [comment]
Rick,

I don’t think I can remove you from it.  It’s a public repo so you may be getting notifications because you forked it or made a comment in the repo at one time.  Try visiting un-watching repos or accounts here: https://github.com/settings/notifications.



Greg Palmier | Operations Engineer

11 East Madison St Floor 4 | Chicago, IL 60602
E  greg.palmier@raise.com


    
raise.com | mobile | press 

On February 22, 2016 at 10:49:54 AM, Rick Alm (notifications@github.com) wrote:


Please remove me from the repo

----
Thanks, Rick

<div>-------- Original message --------</div><div>From: leece <notifications@github.com> </div><div>Date:02/22/2016 10:35 AM (GMT-06:00) </div><div>To: CouponTrade/threatstack-chef <threatstack-chef@noreply.github.com> </div><div>Subject: Re: [threatstack-chef] Updating Rule Sets to incoporate Threat Intelligence (#2) </div><div>
</div>@pmahoney-raise possibly, I'd have to defer to @gregpalmier on that one. Either works for me.

**Pull request merged**
